---
title: "2021 NFL Time Average Point Differentials"
description: |
  Updated through Week 12.
author:
  - name: Casey Caprini
date: 11-26-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
library(tidyverse)
library(nflfastR)
library(nfltools)
library(gt)
library(gtExtras)

weekly_2021 <- nfl_mvt_season(year = 2021)
summary_2021 <- nfl_mvt_season_summary(weekly_2021)

summ_tbl <- left_join(summary_2021, teams_colors_logos,
                      by = c("team" = "team_abbr"))

game_results <- nfl_reg_season_summary(year = 2021) %>%
  mutate(games_played = wins + losses + ties) %>%
  unite("Record", wins:ties, sep = "-") %>%
  rename(`Season Point Diff` = season_point_diff) %>%
  mutate(`Average Point Diff` = `Season Point Diff`/games_played) %>%
  select(team, Record, `Season Point Diff`, `Average Point Diff`)

weeks_played <- weekly_2021 %>%
  filter(is.na(home_away) == FALSE) %>%
  distinct(week) %>%
  summarize(weeks = max(week)) %>%
  pull(weeks)
```

```{r, echo=FALSE}
summ_tbl %>%
  select(team, team_wordmark, adj_mean_point_diff, opp_mean_point_diff) %>%
  arrange(desc(adj_mean_point_diff)) %>%
  left_join(game_results,
            by = c("team" = "team")) %>%
  mutate(rank = row_number(desc(adj_mean_point_diff)),
         adj_mean_point_diff = round(adj_mean_point_diff, 1),
         opp_mean_point_diff = round(opp_mean_point_diff, 1),
         `Avg Point Diff` = round(`Average Point Diff`, 1),
         `Avg Point Diff Rank` = row_number(desc(`Avg Point Diff`))) %>%
  select(rank,
         team_wordmark,
         adj_mean_point_diff,
         opp_mean_point_diff,
         Record,
         `Season Point Diff`,
         `Avg Point Diff`,
         `Avg Point Diff Rank`) %>%
  rename(Team = team_wordmark,
         Rank = rank,
         `Adj Time Average Point Diff` = adj_mean_point_diff,
         `Opponent Quality` = opp_mean_point_diff) %>%
  gt() %>%
  tab_header(title = "2021 NFL Time Average Point Differential",
             subtitle = paste0("Through Week ",
                               weeks_played,
                               ". Regulation only. Data via nflfastR. Table via gt and gtExtras.")) %>%
  cols_align(align = "center") %>%
  gt_img_rows(Team)
```





